### ISSUE TITLE
[FIX] Poll Loading Up on "Post New Discussion" Page

### ISSUE THREAD

**Issue by austins** [hgtonight/DiscussionPolls#1]
**Problem**: The first poll gets loaded up when a creating **new** discussion. Reproducible on both Vanilla 2.0.18.8 and 2.1b1.

**Version**: DiscussionPolls 1.0.1

**Cause**:
DiscussionPollsModel()::GetByDiscussionID() shouldn't get called when $Sender->Discussion->DiscussionID is NULL in method PostController_DiscussionFormOptions_Handler().

**Fix**:
Open this file: `/plugins/DiscussionPolls/class.discussionpolls.plugin.php`

Find this block on lines 216-218:

```
    // Load up existing poll data
    $DPModel = new DiscussionPollsModel();
    $DiscussionPoll = $DPModel->GetByDiscussionID($Sender->Discussion->DiscussionID);
```

Replace it with:

```
    // Load up existing poll data
    if($Sender->Discussion->DiscussionID != NULL) {
      $DPModel = new DiscussionPollsModel();
      $DiscussionPoll = $DPModel->GetByDiscussionID($Sender->Discussion->DiscussionID);
    }
```

**Comment by hgtonight** [comment]
Fixed via x00's pull request
